const addressConfig = {
    MALAYSIA: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: true,
        district: false,
        postcode: true,
        zipcode: false,
        state: true,
        province: false,
    },
    SINGAPORE: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: true,
        district: false,
        postcode: true,
        zipcode: false,
        state: false,
        province: false,
    },
    INDONESIA: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: true,
        district: false,
        postcode: true,
        zipcode: false,
        state: true,
        province: true,
    },
    THAILAND: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: true,
        district: false,
        postcode: true,
        zipcode: false,
        state: false,
        province: true,
    },
    VIETNAM: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: true,
        zipcode: false,
        state: false,
        province: true,
    },
    PHILIPPINES: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: false,
        zipcode: true,
        state: false,
        province: true,
    },
    CAMBODIA: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: true,
        zipcode: false,
        state: false,
        province: true,
    },
    HONG_KONG: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: false,
        zipcode: false,
        state: false,
        province: false,
    },
    UNITED_STATES_OF_AMERICA: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: false,
        zipcode: false,
        state: false,
        province: false,
    },
    JAPAN: {
        unit: true,
        floor: true,
        building: true,
        street: true,
        city: false,
        district: true,
        postcode: false,
        zipcode: false,
        state: false,
        province: false,
    },
};
export default addressConfig;
