const currencySettings = {
    MYR: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "RM",
        code: "MYR",
        signPosition: "BEFORE",
    },
    IDR: {
        displayFormat: "0,0",
        inputFormat: "0[.0000]",
        sign: "Rp",
        code: "IDR",
        signPosition: "BEFORE",
    },
    HKD: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "HK$",
        code: "HKD",
        signPosition: "BEFORE",
    },
    SGD: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "$",
        code: "SGD",
        signPosition: "BEFORE",
    },
    THB: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "฿",
        code: "THB",
        signPosition: "BEFORE",
    },
    VND: {
        displayFormat: "0,0",
        inputFormat: "0[.0000]",
        sign: "₫",
        code: "VND",
        signPosition: "AFTER",
    },
    PHP: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "₱",
        code: "PHP",
        signPosition: "BEFORE",
    },
    KHR: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "៛",
        code: "KHR",
        signPosition: "BEFORE",
    },
    AUD: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "$",
        code: "AUD",
        signPosition: "BEFORE",
    },
    USD: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "$",
        code: "USD",
        signPosition: "BEFORE",
    },
    NZD: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "$",
        code: "NZD",
        signPosition: "BEFORE",
    },
    CNY: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "¥",
        code: "CNY",
        signPosition: "BEFORE",
    },
    GBP: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "£",
        code: "GBP",
        signPosition: "BEFORE",
    },
    EUR: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "€",
        code: "EUR",
        signPosition: "BEFORE",
    },
    NOK: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "kr",
        code: "NOK",
        signPosition: "AFTER",
    },
    JPY: {
        displayFormat: "0,0",
        inputFormat: "0[.0000]",
        sign: "¥",
        code: "JPY",
        signPosition: "BEFORE",
    },
    AZN: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "₼",
        code: "AZN",
        signPosition: "AFTER",
    },
    SEK: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "kr",
        code: "SEK",
        signPosition: "AFTER",
    },
    INR: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "₹",
        code: "INR",
        signPosition: "BEFORE",
    },
    CHF: {
        displayFormat: "0,0.00[00]",
        inputFormat: "0.00[00]",
        sign: "₣",
        code: "CHF",
        signPosition: "BEFORE",
    },
};

export default currencySettings;
