name: "Publish"

# on:
#   push:
#     branches:
#       - master

on:
    pull_request:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
            version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - run: pnpm i --frozen-lock

      # - uses: JS-DevTools/npm-publish@v4
      #   with:
      #     token: ${{ secrets.NPM_AUTH_TOKEN_VUE3 }}
      #     access: public
